spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
file:
  path: E:/file/pilipili/
  domain:
server:
  port: 9004
  servlet:
    context-path: /file
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
oss:
  accessKeyId: LTAI4FyRfMYtnQpHuXao58CE
  accessKeySecret: KPILKCpx5AvxOZI7wWX8RkCh5qx0v6
  endpoint: http://oss-cn-guangzhou.aliyuncs.com
  domain: http://online-pilipili.oss-cn-guangzhou.aliyuncs.com
  bucket: online-pilipili