spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/pilipili?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true
    username: root
    password:
  redis:
    host: localhost
    password:
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
logging:
  level:
    com.course.server.mapper: trace
