spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.4.110.247:3306/pilipili?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true
    username: pilipiliUser
    password: 123456
  redis:
    host: 10.4.110.247
    password:
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
logging:
  level:
    com.course.server.mapper: trace
