spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pilipili?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 153440
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
logging:
  level:
    com.course.server.mapper: trace
