spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.199.53.219/pilipili?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true
    username: root
    password: Zx1534408497..
  redis:
    host: 121.199.53.219
    password: 123456
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
logging:
  level:
    com.course.server.mapper: trace
