spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes[0]:
        id: system
        uri: lb://system
        predicates[0]:
          name: Path
          args[0]: /system/**
      routes[1]:
        id: business
        uri: lb://business
        predicates[0]:
          name: Path
          args[0]: /business/**
      routes[2]:
        id: file
        uri: lb://file
        predicates[0]:
          name: Path
          args[0]: /file/**
    redis:
        host: 121.199.53.219
        password: 123456
        port: 6379

server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
